# Generated by Django 4.0.8 on 2022-11-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.IntegerField()),
                ('garden', models.IntegerField()),
                ('candybar', models.IntegerField()),
                ('games', models.IntegerField()),
                ('wine', models.IntegerField()),
                ('premiumphoto', models.IntegerField()),
                ('premiumvideo', models.IntegerField()),
                ('limo', models.IntegerField()),
                ('stuff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('guests', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('venue', models.BooleanField(default=True)),
                ('garden', models.BooleanField(default=False)),
                ('candybar', models.BooleanField(default=False)),
                ('games', models.BooleanField(default=False)),
                ('wine', models.BooleanField(default=False)),
                ('premiumphoto', models.BooleanField(default=False)),
                ('premiumvideo', models.BooleanField(default=False)),
                ('limo', models.BooleanField(default=False)),
                ('stuff', models.BooleanField(default=False)),
                ('totalprice', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
