# Generated by Django 4.0.8 on 2022-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_chosen_services_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
