# Generated by Django 4.0.8 on 2022-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_service_service_image_alter_venue_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.FileField(null=True, upload_to='weddingmanager/static/images/display/service_files'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_image',
            field=models.FileField(null=True, upload_to='weddingmanager/static/images/display/venue_files'),
        ),
    ]
