# Generated by Django 4.0.8 on 2022-12-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_service_service_image_alter_venue_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_image',
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ManyToManyField(blank=True, null=True, to='orders.file'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.ManyToManyField(blank=True, null=True, to='orders.file'),
        ),
    ]
