# Generated by Django 4.0.8 on 2022-12-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        ('orders', '0019_file_remove_service_service_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='services',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_image',
        ),
        migrations.AlterField(
            model_name='order',
            name='chosen_services',
            field=models.ManyToManyField(blank=True, null=True, to='venues.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
