# Generated by Django 4.0.8 on 2022-12-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_service_slug'),
        ('orders', '0020_remove_service_service_image_remove_venue_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='chosen_services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'venues__in': [models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue')]}, null=True, to='venues.service'),
        ),
    ]
