# Generated by Django 4.0.8 on 2022-12-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_service_slug'),
        ('orders', '0023_order_date_alter_order_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue'),
        ),
    ]
