# Generated by Django 4.0.8 on 2022-12-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_order_date_alter_order_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
