# Generated by Django 4.0.8 on 2023-01-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
        ('orders', '0027_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chosen_decor_items',
            field=models.ManyToManyField(blank=True, to='theme.decoritem'),
        ),
    ]
