# Generated by Django 4.0.8 on 2022-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_order_services_venue_remove_event_user_delete_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(null=True, to='planner.services'),
        ),
    ]
