# Generated by Django 4.0.8 on 2022-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_remove_venue_services_venue_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_price',
            field=models.FloatField(null=True),
        ),
    ]
