# Generated by Django 4.0.8 on 2022-12-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_order_venue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='services',
            new_name='chosen_services',
        ),
    ]
