# Generated by Django 4.0.8 on 2022-12-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_venue_parking_spaces_venue_surface_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='parking_spaces',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='surface_area',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
