# Generated by Django 4.0.8 on 2022-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_venue_parking_spaces_alter_venue_surface_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='chosen_services',
            field=models.ManyToManyField(blank=True, null=True, to='planner.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
