# Generated by Django 4.0.8 on 2023-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoritem',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
