# Generated by Django 4.0.8 on 2023-01-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_remove_decoritem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoritem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.item'),
        ),
    ]
