# Generated by Django 4.0.8 on 2022-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('capacity', models.IntegerField()),
                ('surface_area', models.IntegerField()),
                ('parking_spaces', models.IntegerField()),
                ('venue_price', models.FloatField(null=True)),
                ('services', models.ManyToManyField(to='venues.service')),
            ],
        ),
    ]
