# Generated by Django 4.0.8 on 2022-12-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
