# Generated by Django 4.0.8 on 2022-12-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_service_service_image_venue_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('venue', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venues.service')),
            ],
        ),
    ]
