# Generated by Django 4.0.8 on 2022-12-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_venuefile_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
