# Generated by Django 4.0.8 on 2022-12-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_rename_name_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(),
        ),
    ]
