# Generated by Django 4.0.8 on 2022-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_rename_price_service_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_price',
            field=models.IntegerField(null=True),
        ),
    ]
